<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWindowsForms>True</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="data\**" />
    <EmbeddedResource Remove="data\**" />
    <None Remove="data\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="ElevatorDataEngine.cs" />
    <Compile Remove="FileAuditSystem.cs" />
    <Compile Remove="GemDataEngine.cs" />
    <Compile Remove="MapDataEngine.cs" />
    <Compile Remove="SandboxTestHarness.cs" />
    <Compile Remove="SessionLogger.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Raylib-cs" Version="8.1.0" />
  </ItemGroup>

  <ItemGroup>
    <EditorConfigFiles Remove="C:\Users\neg1s\source\repos\cSharpRaylib\.editorconfig" />
  </ItemGroup>

  <ItemGroup>
    <None Include="C:\Users\neg1s\source\repos\cSharpRaylib\.editorconfig" />
  </ItemGroup>

</Project>
